# pip install pre-commit
# pre-commit install
# pre-commit run --all-files

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-vcs-permalinks
      - id: debug-statements
      - id: end-of-file-fixer
        exclude: tests/test_changes/
        files: \.(py|sh|rst|yml|yaml)$
      - id: mixed-line-ending
      - id: trailing-whitespace
        files: \.(py|sh|rst|yml|yaml)$
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.2
    hooks:
      - id: pyupgrade
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    rev: 5.11.5
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.263"
    hooks:
      - id: ruff
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.5.3
    hooks:
      - id: nbqa-black
        additional_dependencies:
          - "setuptools"
          - "black>=23.1.0"
      - id: nbqa-pyupgrade
        args: [--py38-plus]
        additional_dependencies:
          - "setuptools"
          - "pyupgrade"
      - id: nbqa-isort
        additional_dependencies:
          - "setuptools"
          - "isort"
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.2.0
    hooks:
      - id: mypy
        files: ^pixivpy3/
        additional_dependencies:
          - types-requests
        args: [--show-error-codes, --pretty, --strict]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.7.1"
    hooks:
      - id: prettier
        types_or: [markdown, toml]
        args: [--prose-wrap=always]
        additional_dependencies:
          - "prettier@2.8.8"
          - "prettier-plugin-toml@0.3.1"
